server:
  servlet:
    context-path: /api
spring:
  application:
    name: Admin API
  #  jackson:
  #      serialization:
  #        fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:admin_db;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

  h2:
    console.enabled: true
springfox:
  documentation:
    auto-startup: false
#  messages:
#      basename: lang/messages
#      use-code-as-default-message: true
#      defaultEncoding: UTF-8
